# Generated by Django 4.2.16 on 2026-09-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version_string", models.CharField(max_length=32, unique=True)),
                ("release_notes", models.TextField(blank=True)),
                ("tfjs_manifest_url", models.CharField(max_length=500)),
                ("baselines_url", models.CharField(blank=True, max_length=500)),
                ("weights_sha256", models.CharField(blank=True, max_length=64)),
                ("input_size", models.PositiveSmallIntegerField(default=128)),
                ("embedding_dim", models.PositiveSmallIntegerField(default=128)),
                ("margin", models.FloatField(default=1.0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
