# Generated by Django 4.2.16 on 2026-09-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("pack", models.CharField(blank=True, max_length=120)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("food_beverage", "Food & beverage"),
                            ("pharmaceutical", "Pharmaceutical"),
                            ("personal_care", "Personal care"),
                            ("demo", "Demo / synthetic"),
                        ],
                        default="food_beverage",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
    ]
