# Generated by Django 4.2.16 on 2026-09-18 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("models_registry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_category", models.SlugField(max_length=120)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("authentic", "Authentic"),
                            ("counterfeit", "Counterfeit"),
                            ("inconclusive", "Inconclusive"),
                        ],
                        max_length=16,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                ("distance", models.FloatField(blank=True, null=True)),
                ("state_code", models.CharField(blank=True, max_length=8)),
                ("lga_code", models.CharField(blank=True, max_length=16)),
                (
                    "geo_lat",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "geo_lng",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("model_version_string", models.CharField(max_length=32)),
                ("backend", models.CharField(blank=True, max_length=16)),
                ("inference_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("client_timestamp", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telemetry_events",
                        to="models_registry.modelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["product_category", "received_at"],
                        name="telemetry_t_product_73ae07_idx",
                    ),
                    models.Index(
                        fields=["state_code", "lga_code"], name="telemetry_t_state_c_b19fbc_idx"
                    ),
                    models.Index(fields=["received_at"], name="telemetry_t_receive_f0adb8_idx"),
                ],
            },
        ),
    ]
